### PR TITLE
fix #42

### LINKED ISSUE #42: Hostpot - Set default view not working .
1. Clicks on "HostPot" have id id "6154"
2. Webpage show 3 image . 
3. Clicks on image at midde and clicks on " Set defaultview "
Actual results : Nothing happen when we change image default view . 
capture 2017-09-03 at 6 09 08

### PR DESCRIPTION
**Pull request by nhanpc**

### CODE REVIEW

File: libraries/controller/tour.php [hunk 1]
```diff
@@ -214,11 +214,13 @@ public function ajaxSaveHotspot()
 		// Rebuild json
 		// var_dump($input->getString('hotspotList')); die();
```
Comment (jooservices) [inline libraries/controller/tour.php]: For next time please never commit with debug code. @nhan27

**Comment by nhan27** [comment]
OMG... I thinks I have make a commit to remove it :| So sorry ...

.:pham.channhan:.
GOD bless and beside you
